//! Build script: embed selected `github/gitignore` templates into the
//! binary at compile time.
//!
//! Reads files from `vendor/github-gitignore/` (a git submodule) and
//! emits `$OUT_DIR/embedded_gitignore.rs`, which `src/templates/embedded.rs`
//! pulls in via `include!`.
//!
//! Categories embedded by this script (10 total) are listed in `CATEGORIES`
//! below. Adding a category requires three things:
//!   1. Append a row to `CATEGORIES`
//!   2. Document the category in the `bundled-templates` spec
//!   3. Map the category in `src/templates/mod.rs`

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

/// Maximum aggregate size of all embedded category content (bytes).
/// Keeps the binary lean; raise deliberately if the budget is too tight.
const MAX_TOTAL_BYTES: usize = 50 * 1024;

/// (cargo identifier, lowercase category key, source path under vendor/).
const CATEGORIES: &[(&str, &str, &str)] = &[
    ("MACOS", "macos", "Global/macOS.gitignore"),
    ("LINUX", "linux", "Global/Linux.gitignore"),
    ("WINDOWS", "windows", "Global/Windows.gitignore"),
    ("VSCODE", "vscode", "Global/VisualStudioCode.gitignore"),
    ("JETBRAINS", "jetbrains", "Global/JetBrains.gitignore"),
    ("RUST", "rust", "Rust.gitignore"),
    ("NODE", "node", "Node.gitignore"),
    ("PYTHON", "python", "Python.gitignore"),
    ("DART", "dart", "Dart.gitignore"),
    ("GO", "go", "Go.gitignore"),
];

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let vendor_dir = PathBuf::from(&manifest_dir).join("vendor/github-gitignore");
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));

    println!("cargo:rerun-if-changed=vendor/github-gitignore");
    println!("cargo:rerun-if-changed=build.rs");

    // Gracefully fail if the submodule has not been checked out.
    let probe = vendor_dir.join("Rust.gitignore");
    if !probe.exists() {
        panic!(
            "vendor/github-gitignore/ is empty or missing.\n\
             Run `git submodule update --init --recursive` to fetch the \
             github/gitignore templates referenced by build.rs."
        );
    }

    let mut out = String::new();
    out.push_str(
        "// @generated by build.rs from vendor/github-gitignore/.\n\
         // Do not edit by hand. Run `cargo build` to regenerate.\n\n",
    );

    let mut total_bytes: usize = 0;
    let mut tuple_lines = Vec::new();

    for (ident, key, source_rel) in CATEGORIES {
        let source = vendor_dir.join(source_rel);
        if !source.exists() {
            panic!(
                "build.rs: expected {} to exist under vendor/github-gitignore/",
                source_rel
            );
        }
        let bytes = fs::metadata(&source)
            .unwrap_or_else(|_| panic!("stat {}", source.display()))
            .len() as usize;
        total_bytes += bytes;

        // Use a path relative to OUT_DIR so the generated file's `include_str!`
        // resolves correctly. Cargo's compiler invocation roots `include_str!`
        // at the file performing the include, which is the generated file in
        // OUT_DIR.
        let abs = absolutize(&source);
        out.push_str(&format!(
            "/// {} (~{} bytes)\n\
             pub static {}: &str = include_str!(r#\"{}\"#);\n\n",
            source_rel,
            bytes,
            ident,
            abs.display(),
        ));
        tuple_lines.push(format!("    (\"{}\", {}),", key, ident));
    }

    if total_bytes > MAX_TOTAL_BYTES {
        panic!(
            "build.rs: embedded gitignore content is {} bytes, exceeds the \
             {}-byte budget. Either trim a category or raise MAX_TOTAL_BYTES \
             after review.",
            total_bytes, MAX_TOTAL_BYTES
        );
    }

    out.push_str("/// `(category-key, content)` for every embedded gitignore.\n");
    out.push_str("pub static ALL_CATEGORIES: &[(&str, &str)] = &[\n");
    for line in &tuple_lines {
        out.push_str(line);
        out.push('\n');
    }
    out.push_str("];\n");

    let dest = out_dir.join("embedded_gitignore.rs");
    fs::write(&dest, out).expect("write embedded_gitignore.rs");

    // Sanity nudge for human readers of the build log.
    println!(
        "cargo:warning=embedded {} gitignore categories, {} bytes",
        CATEGORIES.len(),
        total_bytes
    );
}

/// Resolve a path to an absolute, normalized form. We avoid `canonicalize`
/// because that requires the file system to actually contain the path
/// (it does, here) but pulls in symlink resolution we don't need.
fn absolutize(p: &Path) -> PathBuf {
    if p.is_absolute() {
        p.to_path_buf()
    } else {
        let cwd = env::current_dir().unwrap_or_else(|_| PathBuf::from("."));
        cwd.join(p)
    }
}
