# Cargo configuration for PM development

[alias]

# Utility aliases
check-all = "check --workspace --all-targets --all-features"
test-all = "test --workspace --all-targets --all-features"
lint = "clippy --workspace --all-targets --all-features -- -D warnings"

[target.x86_64-unknown-linux-gnu]
# Container-specific optimizations
rustflags = ["-C", "target-cpu=native"]