files:
  - path: rustfmt.toml
    strategy: managed
  - path: clippy.toml
    strategy: managed
  - path: .vscode/settings.json
    strategy: merged
  - path: .vscode/extensions.json
    strategy: merged
