name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
        python-version: [3.8, 3.9, '3.10', '3.11']

    steps:
    - uses: actions/checkout@v4

    # Node.js setup
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Python setup
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    # Install dependencies
    - name: Install Node.js dependencies
      run: |
        if [ -f package.json ]; then
          npm ci
        fi

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        fi
        if [ -f requirements-dev.txt ]; then
          pip install -r requirements-dev.txt
        fi

    # Linting and formatting
    - name: Run ESLint
      run: |
        if [ -f package.json ] && npm list eslint --depth=0 2>/dev/null; then
          npm run lint
        fi

    - name: Run Python linting
      run: |
        if command -v flake8 &> /dev/null; then
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        fi

    # Testing
    - name: Run Node.js tests
      run: |
        if [ -f package.json ] && npm run test --if-present; then
          npm test
        fi

    - name: Run Python tests
      run: |
        if [ -f pytest.ini ] || [ -f pyproject.toml ] || find . -name "test_*.py" | grep -q .; then
          python -m pytest
        fi

    # Security scanning
    - name: Run npm audit
      run: |
        if [ -f package.json ]; then
          npm audit --audit-level moderate
        fi

    - name: Run Python security check
      run: |
        if command -v bandit &> /dev/null; then
          bandit -r . -f json || true
        fi