name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  release-macos:
    runs-on: macos-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build for Apple Silicon
        run: cargo build --release

      - name: Prepare binary
        run: |
          cp target/release/pm pm-aarch64-apple-darwin

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: pm-aarch64-apple-darwin
          token: ${{ secrets.GITHUB_TOKEN }}