name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g., v1.0.0)'
        required: true
        default: 'v0.0.0-manual'
        type: string
      excludes:
        description: 'Comma-separated list of jobs to exclude (e.g., release-windows-x64,release-linux-arm64)'
        required: false
        type: string

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  release-macos-arm64:
    runs-on: macos-latest
    if: "!contains(github.event.inputs.excludes, 'release-macos-arm64')"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Build for macOS ARM64
        run: cargo build --release --target aarch64-apple-darwin
      - name: Prepare binary
        run: cp target/aarch64-apple-darwin/release/pm pm-macos-arm64
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag || github.ref_name }}
          files: pm-macos-arm64
          token: ${{ secrets.GITHUB_TOKEN }}

  release-linux-x64:
    runs-on: ubuntu-latest
    if: "!contains(github.event.inputs.excludes, 'release-linux-x64')"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Build for Linux x64
        run: cargo build --release --target x86_64-unknown-linux-gnu
      - name: Prepare binary
        run: cp target/x86_64-unknown-linux-gnu/release/pm pm-linux-x64
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag || github.ref_name }}
          files: pm-linux-x64
          token: ${{ secrets.GITHUB_TOKEN }}

  release-linux-arm64:
    runs-on: ubuntu-latest
    if: "!contains(github.event.inputs.excludes, 'release-linux-arm64')"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-unknown-linux-gnu
      - name: Set up cross-compilation tools
        run: sudo apt-get update && sudo apt-get install -y gcc-aarch64-linux-gnu
      - name: Build for Linux ARM64
        run: |
          export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc
          cargo build --release --target aarch64-unknown-linux-gnu
      - name: Prepare binary
        run: cp target/aarch64-unknown-linux-gnu/release/pm pm-linux-arm64
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag || github.ref_name }}
          files: pm-linux-arm64
          token: ${{ secrets.GITHUB_TOKEN }}

  release-windows-x64:
    runs-on: windows-latest
    if: "!contains(github.event.inputs.excludes, 'release-windows-x64')"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Build for Windows x64
        run: cargo build --release --target x86_64-pc-windows-msvc
      - name: Prepare binary
        run: cp target/x86_64-pc-windows-msvc/release/pm.exe pm-windows-x64.exe
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag || github.ref_name }}
          files: pm-windows-x64.exe
          token: ${{ secrets.GITHUB_TOKEN }}

  release-windows-arm64:
    runs-on: windows-latest
    if: "!contains(github.event.inputs.excludes, 'release-windows-arm64')"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-pc-windows-msvc
      - name: Build for Windows ARM64
        run: cargo build --release --target aarch64-pc-windows-msvc
      - name: Prepare binary
        run: cp target/aarch64-pc-windows-msvc/release/pm.exe pm-windows-arm64.exe
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag || github.ref_name }}
          files: pm-windows-arm64.exe
          token: ${{ secrets.GITHUB_TOKEN }}

  publish-npm:
    runs-on: ubuntu-latest
    needs: [release-macos-arm64, release-linux-x64, release-windows-x64, release-linux-arm64, release-windows-arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
      - name: Extract version from Cargo.toml
        id: version
        run: |
          VERSION=$(grep '^version = ' Cargo.toml | head -1 | sed 's/version = "\(.*\)"/\1/')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Update package.json version
        run: |
          cd npm
          npm version ${{ steps.version.outputs.version }} --no-git-tag-version
      - name: Install dependencies (skip scripts)
        run: |
          cd npm
          npm install --ignore-scripts
      - name: Build TypeScript
        run: |
          cd npm
          npm run build
      - name: Publish to NPM
        run: |
          cd npm
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
