name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g., v1.0.0)'
        required: true
        type: string

permissions:
  contents: write

jobs:
  release:
    uses: xctions/rust-release/.github/workflows/reusable-rust-release.yml@v2
    with:
      platforms: 'macos-arm64'
      tag_name: ${{ github.event.inputs.tag || github.ref_name }}
      npm_enabled: true
      npm_directory: npm
      npm_tag: dev
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}