name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g., v1.0.0)'
        required: true
        default: 'v0.0.0-manual'
        type: string

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  release-macos:
    runs-on: macos-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build for Apple Silicon
        run: cargo build --release

      - name: Prepare binary
        run: |
          cp target/release/pm pm-aarch64-apple-darwin

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag || github.ref_name }}
          files: |
            pm-aarch64-apple-darwin
            script/install.sh
            script/install-portable.sh
          token: ${{ secrets.GITHUB_TOKEN }}