name: Release

on:
  release:
    types: [published]

jobs:
  publish:
    uses: xctions/rust-npm-publisher/.github/workflows/publish.yml@main
    with:
      binaries: "pm"
      npm_package_name: "@zdpk/pm"
      version: ${{ github.ref_name }}
      platforms: "macos-arm64,macos-x64,linux-x64,windows-x64"
      npm_directory: "npm"
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}